name: edufy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  google_generative_ai: ^0.4.6
  flutter_gemini: ^2.0.5
  image_picker: ^1.1.2
  dash_chat_2: ^0.0.21
  flutter_dotenv: ^5.0.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.0


flutter:
  uses-material-design: true
  assets:
    - lib/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/images/logo.png"